// 카드 풀 정의 (몬스터 20장 + 마법 6장 + 함정 4장 = 30장)
const CARD_POOL = [
  // ---- 몬스터 ---- (효과 텍스트는 분위기 연출용 설명이지만, 소환/전투/묘지 트리거로 실제 로직에도 반영됨)
  // level 4 이하: 릴리스 없이 일반 소환/세트. level 5-6: 1장 릴리스. level 7-8: 2장 릴리스.
  { id: 'm01', name: '흑염의 드래곤', type: 'monster', atk: 3000, def: 2500, level: 8, image: 'cards/m01.jpg', description: '이 카드가 일반 소환/특수 소환에 성공했을 때, 상대 필드의 모든 몬스터를 파괴한다.' },
  { id: 'm02', name: '빛의 성기사', type: 'monster', atk: 2500, def: 2000, level: 6, image: 'cards/m02.jpg', description: '이 카드가 전투로 몬스터를 파괴했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'm03', name: '심연의 마물', type: 'monster', atk: 2200, def: 1800, level: 5, image: 'cards/m03.jpg', description: '이 카드가 특수 소환에 성공했을 때, 상대 필드의 몬스터 1장의 효과를 무효로 한다.' },
  { id: 'm04', name: '불꽃의 피닉스', type: 'monster', atk: 2400, def: 1600, level: 6, image: 'cards/m04.jpg', description: '이 카드가 묘지로 보내졌을 경우, 자신의 묘지에서 레벨 4 이하의 몬스터 1장을 특수 소환할 수 있다.' },
  { id: 'm05', name: '대지의 골렘', type: 'monster', atk: 2600, def: 2200, level: 7, image: 'cards/m05.jpg', description: '이 카드가 일반 소환에 성공했을 때, 자신의 덱에서 "대지" 속성 몬스터 1장을 묘지로 보낼 수 있다.' },
  { id: 'm06', name: '바람의 요정', type: 'monster', atk: 1800, def: 1200, level: 4, image: 'cards/m06.jpg', description: '이 카드가 일반 소환에 성공했을 때, 자신 필드의 모든 마법/함정 카드를 다시 발동할 수 있다.' },
  { id: 'm07', name: '어둠의 사신', type: 'monster', atk: 2000, def: 1500, level: 5, image: 'cards/m07.jpg', description: '이 카드가 전투로 몬스터를 파괴했을 때, 상대의 묘지의 몬스터 1장을 제외한다.' },
  { id: 'm08', name: '전공의 용', type: 'monster', atk: 2800, def: 2400, level: 7, image: 'cards/m08.jpg', description: '이 카드가 특수 소환에 성공했을 때, 자신 필드의 모든 몬스터의 공격력은 500 올라간다.' },
  { id: 'm09', name: '지옥의 군주', type: 'monster', atk: 2700, def: 2000, level: 7, image: 'cards/m09.jpg', description: '이 카드가 소환에 성공했을 때, 상대 필드의 몬스터 1장을 지정하여 공격력을 0으로 한다.' },
  { id: 'm10', name: '달의 늑대', type: 'monster', atk: 2000, def: 1400, level: 5, image: 'cards/m10.jpg', description: '이 카드가 전투로 몬스터를 파괴했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'm11', name: '번개 사냥꾼', type: 'monster', atk: 2300, def: 1600, level: 5, image: 'cards/m11.jpg', description: '이 카드가 공격 선언했을 때, 상대 필드의 마법/함정 카드 1장을 선택하여 파괴한다.' },
  { id: 'm12', name: '저주받은 인어', type: 'monster', atk: 1600, def: 1200, level: 4, image: 'cards/m12.jpg', description: '이 카드가 묘지에 존재할 경우, 자신의 턴에 1번, 몬스터 1장의 효과를 무효로 할 수 있다.' },
  { id: 'm13', name: '시간의 마도사', type: 'monster', atk: 1800, def: 1000, level: 4, image: 'cards/m13.jpg', description: '이 카드가 소환에 성공했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'm14', name: '죽음의 기사', type: 'monster', atk: 2100, def: 1500, level: 5, image: 'cards/m14.jpg', description: '이 카드가 전투로 몬스터를 파괴했을 때, 상대의 라이프 포인트를 500 감소시킨다.' },
  { id: 'm15', name: '정령의 드루이드', type: 'monster', atk: 1700, def: 1400, level: 5, image: 'cards/m15.jpg', description: '이 카드가 소환에 성공했을 때, 자신 필드의 "정령" 몬스터 1장을 특수 소환할 수 있다.' },
  { id: 'm16', name: '용암의 거인', type: 'monster', atk: 2500, def: 2000, level: 6, image: 'cards/m16.jpg', description: '이 카드가 소환에 성공했을 때, 상대 필드의 몬스터 1장을 선택하여 공격력을 1000 감소시킨다.' },
  { id: 'm17', name: '얼음의 여왕', type: 'monster', atk: 2200, def: 1800, level: 6, image: 'cards/m17.jpg', description: '이 카드가 특수 소환에 성공했을 때, 상대 필드의 몬스터 전체의 공격력을 500 감소시킨다.' },
  { id: 'm18', name: '광기의 광대', type: 'monster', atk: 1900, def: 1500, level: 4, image: 'cards/m18.jpg', description: '이 카드가 소환에 성공했을 때, 상대는 패 1장을 묘지로 보내고 덱에서 1장 드로우한다.' },
  { id: 'm19', name: '유령선', type: 'monster', atk: 2300, def: 1800, level: 6, image: 'cards/m19.jpg', description: '이 카드가 묘지로 보내졌을 때, 자신 필드에 "바다" 속성 몬스터 1장을 특수 소환할 수 있다.' },
  { id: 'm20', name: '하늘을 나는 섬', type: 'monster', atk: 2400, def: 2000, level: 6, image: 'cards/m20.jpg', description: '이 카드가 소환에 성공했을 때, 자신 필드의 모든 몬스터의 수비력을 500 올린다.' },

  // ---- 몬스터 (초강력 개체, 릴리스 2장) ----
  { id: 'f01', name: '심연의 창조신 아자토스', type: 'monster', atk: 4000, def: 4000, level: 12, image: 'cards/f01.jpg', description: '어둠 속성. 이 카드가 소환에 성공했을 때, 상대 필드의 모든 몬스터를 파괴한다.' },
  { id: 'f02', name: '천계의 성녀 세레네', type: 'monster', atk: 3500, def: 3000, level: 11, image: 'cards/f02.jpg', description: '빛 속성. 이 카드가 소환에 성공했을 때, 상대 필드의 몬스터 1장을 파괴한다.' },
  { id: 'f03', name: '붕괴의 용암룡 바알가', type: 'monster', atk: 3600, def: 2800, level: 11, image: 'cards/f03.jpg', description: '화염 속성. 이 카드가 소환에 성공했을 때, 상대의 세트된 마법/함정 카드 1장을 파괴한다.' },
  { id: 'f04', name: '달의 이계신 엘리시온', type: 'monster', atk: 3200, def: 2600, level: 10, image: 'cards/f04.jpg', description: '물 속성. 이 카드가 소환에 성공했을 때, 상대 필드의 몬스터 1장을 패로 되돌린다.' },
  { id: 'sy01', name: '별을 잇는 자 루미네로', type: 'monster', atk: 3000, def: 2500, level: 9, image: 'cards/sy01.jpg', description: '빛 속성. 이 카드가 소환에 성공했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'sy02', name: '심연의 기사 가이마스', type: 'monster', atk: 3200, def: 2800, level: 9, image: 'cards/sy02.jpg', description: '어둠 속성. 이 카드가 소환에 성공했을 때, 상대의 세트 몬스터 1장을 앞면 공격 표시로 강제로 바꾼다.' },
  { id: 'x01', name: '어둠을 먹는 별의 용', type: 'monster', atk: 3500, def: 3000, level: 11, image: 'cards/x01.jpg', description: '어둠 속성. 이 카드가 소환에 성공했을 때, 상대의 묘지를 모두 제외한다.' },
  { id: 'x02', name: '시간을 거스르는 자 카이로스', type: 'monster', atk: 3100, def: 2700, level: 9, image: 'cards/x02.jpg', description: '빛 속성. 이 카드가 소환에 성공했을 때, 상대 필드의 몬스터 1장의 효과를 무효화한다.' },
  { id: 'x03', name: '바다의 지배자 네프티스', type: 'monster', atk: 3000, def: 2500, level: 9, image: 'cards/x03.jpg', description: '물 속성. 이 카드가 소환에 성공했을 때, 자신의 라이프 포인트를 1000 회복한다.' },

  // ---- 몬스터 (강력 개체, 릴리스 1장) ----
  { id: 'f05', name: '기계왕 알케스트로스', type: 'monster', atk: 2500, def: 2100, level: 6, image: 'cards/f05.jpg', description: '땅 속성. 이 카드가 소환에 성공했을 때, 상대 필드의 몬스터 1장을 파괴한다.' },
  { id: 'sy03', name: '바람을 타는 성룡 아스트라', type: 'monster', atk: 2900, def: 2400, level: 8, image: 'cards/sy03.jpg', description: '바람 속성. 이 카드가 소환에 성공했을 때, 상대 필드 몬스터 전체의 공격력을 500 감소시킨다.' },
  { id: 'sy04', name: '지옥의 군주 잔타르크', type: 'monster', atk: 2800, def: 2200, level: 8, image: 'cards/sy04.jpg', description: '화염 속성. 이 카드가 소환에 성공했을 때, 상대 필드의 몬스터 1장을 게임에서 제외한다.' },
  { id: 'x04', name: '황혼의 암살자 크로노스', type: 'monster', atk: 2800, def: 2400, level: 8, image: 'cards/x04.jpg', description: '어둠 속성. 이 카드가 전투로 몬스터를 파괴했을 때, 상대 묘지의 카드 1장을 제외한다.' },
  { id: 'x05', name: '무한의 기개신 알파리온', type: 'monster', atk: 2600, def: 3200, level: 7, image: 'cards/x05.jpg', description: '땅 속성. 이 카드가 소환에 성공했을 때, 상대 필드 몬스터 1장의 공격력 500을 빼앗아 자신 필드 몬스터에게 더한다.' },
  { id: 'l01', name: '하늘을 나는 용 벨테로스', type: 'monster', atk: 2500, def: 2000, level: 6, image: 'cards/l01.jpg', description: '바람 속성. 이 카드가 소환에 성공했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'l02', name: '심연의 감시자 세리온', type: 'monster', atk: 2400, def: 1900, level: 6, image: 'cards/l02.jpg', description: '어둠 속성. 이 카드가 소환에 성공했을 때, 상대 필드의 몬스터 1장의 효과를 무효화한다.' },
  { id: 'l03', name: '대지의 파수장 멜레온', type: 'monster', atk: 2300, def: 1800, level: 5, image: 'cards/l03.jpg', description: '땅 속성. 이 카드가 소환에 성공했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'l04', name: '공허의 정찰 노바', type: 'monster', atk: 2200, def: 1700, level: 5, image: 'cards/l04.jpg', description: '빛 속성. 이 카드가 소환에 성공했을 때, 상대 패에서 카드 1장을 무작위로 묘지로 보낸다.' },
  { id: 'l05', name: '대지의 수호자 가이아스', type: 'monster', atk: 2100, def: 1600, level: 5, image: 'cards/l05.jpg', description: '땅 속성. 이 카드가 전투로 몬스터를 파괴했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'l06', name: '빛의 인도자 에리시온', type: 'monster', atk: 2000, def: 1500, level: 5, image: 'cards/l06.jpg', description: '빛 속성. 이 카드가 소환에 성공했을 때, 자신의 라이프 포인트를 500 회복한다.' },
  { id: 'l07', name: '권력의 심판 노바', type: 'monster', atk: 2100, def: 1600, level: 5, image: 'cards/l07.jpg', description: '어둠 속성. 이 카드가 전투로 몬스터를 파괴했을 때, 상대의 라이프 포인트를 500 감소시킨다.' },

  // ---- 몬스터 (저비용 서치/전개 보조, 릴리스 없음) ----
  { id: 'n01', name: '빛의 인도자', type: 'monster', atk: 1500, def: 1200, level: 4, image: 'cards/n01.jpg', description: '빛 속성. 이 카드가 소환에 성공했을 때, 덱에서 몬스터 1장을 패에 넣는다.' },
  { id: 'n02', name: '달의 사냥꾼', type: 'monster', atk: 1400, def: 1000, level: 4, image: 'cards/n02.jpg', description: '어둠 속성. 이 카드가 전투로 몬스터를 파괴했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'n03', name: '바람의 정령사', type: 'monster', atk: 1200, def: 800, level: 3, image: 'cards/n03.jpg', description: '바람 속성. 이 카드가 특수 소환에 성공했을 때, 상대의 세트 카드 1장을 파괴한다.' },
  { id: 'n04', name: '암흑의 수호자', type: 'monster', atk: 1600, def: 1200, level: 4, image: 'cards/n04.jpg', description: '어둠 속성. 이 카드가 소환에 성공했을 때, 자신 필드 몬스터 전체의 공격력이 300 상승한다.' },
  { id: 'n05', name: '화염의 이계인', type: 'monster', atk: 1300, def: 1000, level: 4, image: 'cards/n05.jpg', description: '화염 속성. 이 카드가 묘지로 보내졌을 경우, 자신 필드에서 가장 강한 몬스터의 공격력이 500 상승한다.' },
  { id: 'n06', name: '얼음의 사제', type: 'monster', atk: 1200, def: 1500, level: 4, image: 'cards/n06.jpg', description: '물 속성. 이 카드가 일반 소환에 성공했을 때, 자신 덱의 맨 위 카드 1장을 묘지로 보낸다.' },
  { id: 'n07', name: '기계의 전사', type: 'monster', atk: 1400, def: 1200, level: 4, image: 'cards/n07.jpg', description: '땅 속성. 이 카드가 특수 소환에 성공했을 때, 상대 몬스터 1장의 효과를 무효화한다.' },
  { id: 'n08', name: '나락의 서린자', type: 'monster', atk: 1000, def: 1800, level: 4, image: 'cards/n08.jpg', description: '어둠 속성. 이 카드가 묘지로 보내졌을 경우, 덱에서 몬스터 1장을 패에 넣는다.' },
  { id: 'n09', name: '숲의 수호자', type: 'monster', atk: 1100, def: 1600, level: 4, image: 'cards/n09.jpg', description: '바람 속성. 이 카드가 소환에 성공했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'n10', name: '회색의 기사', type: 'monster', atk: 1300, def: 900, level: 3, image: 'cards/n10.jpg', description: '빛 속성. 이 카드가 전투로 몬스터를 파괴했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'n11', name: '번개의 정령', type: 'monster', atk: 1000, def: 1500, level: 3, image: 'cards/n11.jpg', description: '빛 속성. 이 카드가 일반 소환에 성공했을 때, 상대의 세트 카드 1장을 파괴한다.' },
  { id: 'n12', name: '어둠의 마도사', type: 'monster', atk: 1200, def: 1000, level: 3, image: 'cards/n12.jpg', description: '어둠 속성. 이 카드가 특수 소환에 성공했을 때, 자신 묘지의 마법 카드 1장을 패에 넣는다.' },
  { id: 'n13', name: '고대의 전령', type: 'monster', atk: 1500, def: 1100, level: 4, image: 'cards/n13.jpg', description: '땅 속성. 이 카드가 일반 소환에 성공했을 때, 자신 필드의 다른 몬스터 중 가장 강한 몬스터의 공격력이 500 상승한다.' },
  { id: 'n14', name: '빛의 종자기사', type: 'monster', atk: 1200, def: 1600, level: 4, image: 'cards/n14.jpg', description: '빛 속성. 이 카드가 전투로 몬스터를 파괴했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'n15', name: '장미의 소녀', type: 'monster', atk: 1000, def: 1400, level: 3, image: 'cards/n15.jpg', description: '바람 속성. 이 카드가 특수 소환에 성공했을 때, 자신 덱의 맨 위 카드 1장을 묘지로 보낸다.' },
  { id: 'n16', name: '유성의 마도사', type: 'monster', atk: 1200, def: 800, level: 3, image: 'cards/n16.jpg', description: '화염 속성. 이 카드가 일반 소환에 성공했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'n17', name: '지하의 탐색자', type: 'monster', atk: 1200, def: 600, level: 3, image: 'cards/n17.jpg', description: '화염 속성. 이 카드가 일반 소환에 성공했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'n18', name: '저하의 탐색자', type: 'monster', atk: 1000, def: 1200, level: 3, image: 'cards/n18.jpg', description: '땅 속성. 이 카드가 묘지로 보내졌을 경우, 덱에서 레벨 4 이하의 몬스터 1장을 특수 소환할 수 있다.' },
  { id: 'n19', name: '해황의 부하', type: 'monster', atk: 1200, def: 1000, level: 3, image: 'cards/n19.jpg', description: '땅 속성. 이 카드가 일반 소환에 성공했을 때, 자신은 덱에서 1장 드로우한다.' },
  { id: 'n20', name: '사역의 기사', type: 'monster', atk: 1000, def: 1200, level: 3, image: 'cards/n20.jpg', description: '어둠 속성. 이 카드가 특수 소환에 성공했을 때, 자신 필드 몬스터 전체의 공격력이 500 상승한다.' },

  // ---- 마법 ----
  { id: 's01', name: '파이어볼', type: 'spell', effect: 'damage', value: 800, emoji: '🔥', description: '상대에게 800 데미지를 입힌다.' },
  { id: 's02', name: '라이트닝 볼트', type: 'spell', effect: 'damage', value: 800, emoji: '💥', description: '상대에게 800 데미지를 입힌다.' },
  { id: 's03', name: '회복의 빛', type: 'spell', effect: 'heal', value: 800, emoji: '✨', description: '내 라이프를 800 회복한다.' },
  { id: 's04', name: '생명의 샘', type: 'spell', effect: 'heal', value: 800, emoji: '💧', description: '내 라이프를 800 회복한다.' },
  { id: 's05', name: '힘의 축복', type: 'spell', effect: 'buff', value: 500, emoji: '💪', description: '내 몬스터 1장의 공격력을 500 올린다.' },
  { id: 's06', name: '지혜의 서', type: 'spell', effect: 'draw', value: 2, emoji: '📖', description: '카드를 2장 뽑는다.' },

  // ---- 마법 (서치 / 전개 / 특수소환 보조) ----
  { id: 'sp01', name: '성스러운 서약', type: 'spell', effect: 'tutor', emoji: '📜', description: '덱에서 몬스터 1장을 패에 넣는다.' },
  { id: 'sp02', name: '전개 준비', type: 'spell', effect: 'ssDeck', emoji: '🌀', description: '덱에서 레벨 4 이하의 몬스터 1장을 특수 소환한다.' },
  { id: 'sp03', name: '융합의 재료', type: 'spell', effect: 'mill', emoji: '⚙️', description: '덱의 맨 위 카드 1장을 묘지로 보낸다.' },
  { id: 'sp04', name: '증원의 기도', type: 'spell', effect: 'tutorDraw', emoji: '🙏', description: '덱에서 몬스터 1장을 패에 넣고, 자신은 1장 드로우한다.' },
  { id: 'sp05', name: '신속한 전개', type: 'spell', effect: 'ssDeck', emoji: '⚡', description: '덱에서 레벨 4 이하의 몬스터 1장을 특수 소환한다.' },
  { id: 'sp06', name: '드래곤의 계약', type: 'spell', effect: 'buff', value: 500, emoji: '🗡️', description: '내 몬스터 1장의 공격력을 500 올린다.' },
  { id: 'sp07', name: '무한한 가능성', type: 'spell', effect: 'tutorDraw', emoji: '🌌', description: '덱에서 몬스터 1장을 패에 넣고, 자신은 1장 드로우한다.' },
  { id: 'sp08', name: '운명의 연결', type: 'spell', effect: 'ssHand', emoji: '🔗', description: '패에서 몬스터 1장을 특수 소환한다.' },
  { id: 'sp09', name: '별의 인도', type: 'spell', effect: 'buff', value: 500, emoji: '⭐', description: '내 몬스터 1장의 공격력을 500 올린다.' },
  { id: 'sp10', name: '세계를 잇는 문', type: 'spell', effect: 'ssDeck', emoji: '🚪', description: '덱에서 레벨 4 이하의 몬스터 1장을 특수 소환한다.' },

  // ---- 함정 ---- (전부 세트 전용. 세트한 바로 그 턴엔 발동 불가. 상대의 행동에 반응해 자동 발동)
  { id: 't01', name: '반격의 결계', type: 'trap', trapEffect: 'destroyAttacker', emoji: '🛡️', description: '상대가 공격을 선언했을 때 자동 발동한다. 공격 몬스터를 파괴한다.' },
  { id: 't02', name: '경고의 결계', type: 'trap', trapEffect: 'destroySummoned', emoji: '⚠️', description: '상대가 몬스터를 소환했을 때 자동 발동한다. 그 몬스터를 파괴한다.' },
  { id: 't03', name: '마도 봉인함', type: 'trap', trapEffect: 'negateSpell', emoji: '🔒', description: '상대가 마법 카드를 발동했을 때 자동 발동한다. 그 마법의 효과를 무효로 하고 파괴한다.' },
  { id: 't04', name: '응보의 화살', type: 'trap', trapEffect: 'reflectDamage', emoji: '🏹', description: '상대가 공격을 선언했을 때 자동 발동한다. 공격력만큼 상대에게 데미지를 입힌다.' },

  // ---- 함정 (전개 / 방해 / 보호) ----
  { id: 'tp01', name: '신의 축복', type: 'trap', trapEffect: 'healOnAttack', trapValue: 800, emoji: '✨', description: '상대가 공격을 선언했을 때 자동 발동한다. 자신의 라이프 포인트를 800 회복한다.' },
  { id: 'tp02', name: '무한의 장벽', type: 'trap', trapEffect: 'destroySummoned', emoji: '🌐', description: '상대가 몬스터를 소환했을 때 자동 발동한다. 그 몬스터를 파괴한다.' },
  { id: 'tp03', name: '반격의 맹세', type: 'trap', trapEffect: 'destroyAttacker', emoji: '⚔️', description: '상대가 공격을 선언했을 때 자동 발동한다. 공격 몬스터를 파괴한다.' },
  { id: 'tp04', name: '영혼의 빙결', type: 'trap', trapEffect: 'zeroSummonedAtk', emoji: '❄️', description: '상대가 몬스터를 소환했을 때 자동 발동한다. 그 몬스터의 공격력을 0으로 만든다.' },
  { id: 'tp05', name: '전술의 함정', type: 'trap', trapEffect: 'reflectDamage', emoji: '🎯', description: '상대가 공격을 선언했을 때 자동 발동한다. 공격력만큼 상대에게 데미지를 입힌다.' },
  { id: 'tp06', name: '마지막 기회', type: 'trap', trapEffect: 'specialSummonFromDeck', emoji: '🕊️', description: '상대가 공격을 선언했을 때 자동 발동한다. 덱에서 레벨 4 이하의 몬스터 1장을 특수 소환한다.' },
  { id: 'tp07', name: '차원의 균열', type: 'trap', trapEffect: 'specialSummonFromDeck', emoji: '🌀', description: '상대가 몬스터를 소환했을 때 자동 발동한다. 덱에서 레벨 4 이하의 몬스터 1장을 특수 소환한다.' },
  { id: 'tp08', name: '경계의 눈', type: 'trap', trapEffect: 'reflectDamage', emoji: '👁️', description: '상대가 공격을 선언했을 때 자동 발동한다. 공격력만큼 상대에게 데미지를 입힌다.' },
  { id: 'tp09', name: '빛의 장막', type: 'trap', trapEffect: 'destroyAttacker', emoji: '🛡️', description: '상대가 공격을 선언했을 때 자동 발동한다. 공격 몬스터를 파괴한다.' },
  { id: 'tp10', name: '운명의 반향', type: 'trap', trapEffect: 'negateSpellDamage', trapValue: 500, emoji: '🔮', description: '상대가 마법 카드를 발동했을 때 자동 발동한다. 그 마법을 무효로 하고 상대에게 500 데미지를 입힌다.' },
];
